import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from "next/link"
import noImage from '../public/no_image.png'

function Home({ posts }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Movie App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {
        posts.map((post) => {
          return (
            <div key={post.id} className={styles.movieresult}>
              <Link href={`about/${post.id}`}>
                <div key={post.id} className={styles.card}>
                  <Image
                    src={post.poster_path !== null ? `https://www.themoviedb.org/t/p/w220_and_h330_face${post.poster_path}` : noImage}
                    alt={post.title}
                    height={750}
                    width={500}
                  />
                  <div>
                    <span style={{ color: 'white' }}><b>{post.title}</b></span>
                  </div>
                </div>
              </Link>
            </div>
          )
        })

      }
    </div >
  )
}

export default Home;
export async function getStaticProps() {
  const response = await fetch('https://api.themoviedb.org/3/movie/top_rated?api_key=ef2fc7966b7886b23c82a2279f82783c&language=en-US&page=1')
  const data = await response.json()
  const result = data.results
  return {
    props: {
      posts: result,
    }
  }
}
